# dev configuration
dynamodbStack:
  stackName: 'BeerpongoDynamoDbStackDev'
  gamesTable:
    id: 'BeerpongoDevGamesTable'
    tableName: 'BeerpongoDevGamesTable'

lambdaStack:
  stackName: 'BeerpongoLambdaStackDev'
  layer:
    id: "backend_lambda_layer"
    code: "./../backend/lambda_layers/backend_lambda_layer.zip"
    runtime: 'python3.9'
  lambdas:
    lambda_authenticate_websocket:
      name: "lambdaDev_authenticate_websocket"
      code: "./../backend/websocket_lambdas"
      handler: "lambda_authenticate_websocket.on_connect"
      runtime: 'python3.9'
      jwt_layer:
        id: "py39_jwt_authentication_layer"
        code: "./../backend/lambda_layers/pyjwtcrypto_39.zip"
    lambda_on_connect:
      name: "lambdaDev_connect_websocket"
      code: "./../backend/websocket_lambdas"
      handler: "lambda_on_connect.on_connect"
      runtime: "python3.9"
    lambda_on_create_game:
      name: "lambdaDev_createGame"
      code: "./../backend/websocket_lambdas"
      handler: "lambda_on_create_game.on_create_game"
      runtime: "python3.9"
    lambda_on_join_game:
      name: "lambdaDev_joinGame"
      code: "./../backend/websocket_lambdas"
      handler: "lambda_on_join_game.on_join_game"
      runtime: "python3.9"
    lambda_on_update_game:
      name: "lambdaDev_updateGame"
      code: "./../backend/websocket_lambdas"
      handler: "lambda_on_update_game.on_update_game"
      runtime: "python3.9"

cognitoStack:
  stackName: 'BeerpongoCognitoStackDev'
  userPool:
    id: 'BeerpongoDevUserPool'
    name: 'BeerpongoDevUserPool'
  userPoolClient:
    id: 'BeerpongoDevUserPoolClient'
    name: 'BeerpongoDevUserPoolClient'

apiGatewayWebsocketStack:
  stackName: 'BeerpongoAPIGatewayWebsocketStackDev'
  id: 'BeerpongoDevWebsocketApi'
  name: 'BeerpongoDevWebsocketApi'
  authorizerId: 'CognitoUserDevAuthorizer'
  connectRouteIntegrationId: 'ConnectWebsocketIntegrationDev'
  stage:
    id: 'BeerpongoWebsocketStageDev'
    name: 'dev'
  routes:
    createGameRoute:
      id: 'CreateGameIntegrationDev'
      responseId: 'CreateGameIntegrationDev'
      key: 'CreateGame'
    joinGameRoute:
      id: 'JoinGameIntegrationDev'
      responseId: 'JoinGameIntegrationDev'
      key: 'JoinGame'
    updateGameRoute:
      id: 'UpdateGameIntegrationDev'
      responseId: 'UpdateGameIntegrationDev'
      key: 'UpdateGame'