# dev configuration
dynamoDB:
  stackName: 'BeerpongoDynamoDbStackDev'
  gamesTable:
    id: 'BeerpongoDevGamesTable'
    tableName: 'BeerpongoDevGamesTable'

APIGateway:
  stackName: 'BeerpongoAPIGatewayStackDev'
  apiFile: './config/api_beerpongo.json'
  id: 'BeerpongoDev-api'

apiGatewayWebsocket:
  stackName: 'BeerpongoAPIGatewayWebsocketStackDev'
  id: 'BeerpongoDevWebsocketApi'
  name: 'BeerpongoDevWebsocketApi'
  stage:
    id: 'BeerpongoWebsocketStageDev'
    name: 'dev'
  createGameRoute:
    id: 'CreateGameIntegrationDev'
    responseId: 'CreateGameIntegrationDev'
    key: 'CreateGame'
  joinGameRoute:
    id: 'JoinGameIntegrationDev'
    responseId: 'JoinGameIntegrationDev'
    key: 'JoinGame'
  updateGameRoute:
    id: 'UpdateGameIntegrationDev'
    responseId: 'UpdateGameIntegrationDev'
    key: 'UpdateGame'

Lambda:
  stackName: 'BeerpongoLambdaStackDev'
  lambdas:
    lambda_post:
      name: "lambdaDev_post"
      code: "./../backend/rest_lambdas/post_lambda"
      handler: "lambda_post.post"
      runtime: "python3.9"
    lambda_get:
      name: "lambdaDev_get"
      code: "./../backend/rest_lambdas/get_lambda"
      handler: "lambda_get.get"
      runtime: "python3.9"
    lambda_put:
      name: "lambdaDev_put"
      code: "./../backend/rest_lambdas/put_lambda"
      handler: "lambda_put.put"
      runtime: "python3.9"
    lambda_join:
      name: "lambdaDev_join"
      code: "./../backend/rest_lambdas/join_lambda"
      handler: "lambda_join.join"
      runtime: "python3.9"
    lambda_on_create_game:
      name: "lambdaDev_createGame"
      code: "./../backend/websocket_lambdas/lambda_on_create_game"
      handler: "lambda_on_create_game.on_create_game"
      runtime: "python3.9"
    lambda_on_join_game:
      name: "lambdaDev_joinGame"
      code: "./../backend/websocket_lambdas/lambda_on_join_game"
      handler: "lambda_on_join_game.on_join_game"
      runtime: "python3.9"
    lambda_on_update_game:
      name: "lambdaDev_updateGame"
      code: "./../backend/websocket_lambdas/lambda_on_update_game"
      handler: "lambda_on_update_game.on_update_game"
      runtime: "python3.9"

