# dev configuration
dynamoDB:
  stackName: 'BeerpongoDynamoDbStackDev'
  gamesTable:
    id: 'BeerpongoDevGamesTable'
    tableName: 'BeerpongoDevGamesTable'

APIGateway:
  stackName: 'BeerpongoAPIGatewayStackDev'
  apiFile: './config/api_beerpongo.json'
  id: 'BeerpongoDev-api'

apiGatewayWebsocket:
  stackName: 'BeerpongoAPIGatewayWebsocketStackDev'
  id: 'BeerpongoDevWebsocketApi'
  name: 'BeerpongoDevWebsocketApi'
  stage:
    id: 'BeerpongoWebsocketStageDev'
    name: 'dev'
  connectRoute:
    id: 'ConnectGameIntegrationDev'
  disconnectRoute:
    id: 'DisconnectGameIntegrationDev'
  updateGameRoute:
    key: 'updateGame'
    id: 'UpdateGameIntegrationDev'

Lambda:
  stackName: 'BeerpongoLambdaStackDev'
  lambdas:
    lambda_post:
      name: "lambdaDev_post"
      code: "./../backend/post_lambda"
      handler: "lambda_post.post"
      runtime: "python3.9"
    lambda_get:
      name: "lambdaDev_get"
      code: "./../backend/get_lambda"
      handler: "lambda_get.get"
      runtime: "python3.9"
    lambda_put:
      name: "lambdaDev_put"
      code: "./../backend/put_lambda"
      handler: "lambda_put.put"
      runtime: "python3.9"
    lambda_join:
      name: "lambdaDev_join"
      code: "./../backend/join_lambda"
      handler: "join_lambda.join_handler"
      runtime: "python3.9"
    lambda_on_connect:
      name: "lambdaDev_connect"
      code: "./../backend/websocket_lambdas/lambda_on_connect"
      handler: "lambda_on_connect.on_connect"
      runtime: "python3.9"
    lambda_on_disconnect:
      name: "lambdaDev_disconnect"
      code: "./../backend/websocket_lambdas/lambda_on_disconnect"
      handler: "lambda_on_disconnect.on_disconnect"
      runtime: "python3.9"
    lambda_on_update_game:
      name: "lambdaDev_updateGame"
      code: "./../backend/websocket_lambdas/lambda_on_update_game"
      handler: "lambda_on_update_game.on_update_game"
      runtime: "python3.9"

