[tool.pytest.ini_options]
testpaths = "./tests"
pythonpath = [
 "./cdk/"
]

[tool.flake8]
exclude = "cdk.out"

[tool.black]
skip-string-normalization = true
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | cdk.out
)/
'''

[tool.isort]
profile = "black"
skip = ["cdk.out", ".venv"]
line_length=79

[tool.mypy]
mypy_path = "./cdk"
check_untyped_defs = true
no_implicit_optional = true
disallow_untyped_defs = true
show_error_codes = true
warn_unused_ignores = true
disallow_any_unimported = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "boto3.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "botocore.*"
ignore_missing_imports = true
