[tool.pytest.ini_options]
testpaths = "./tests"
pythonpath = [
    "./src"
]
log_cli_level = "INFO"

[tool.flake8]
exclude = "requirements"

[tool.black]
skip-string-normalization = true
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | backend.out
  | requirements
)/
'''

[tool.isort]
profile = "black"
skip = ["backend.out", ".venv", "requirements"]
line_length = 79

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
disallow_untyped_defs = true
show_error_codes = true
warn_unused_ignores = true
disallow_any_unimported = true
warn_return_any = false
exclude = [
    '^test\.'
]

[[tool.mypy.overrides]]
module = "boto3.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "botocore.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jwt.*"
ignore_missing_imports = true