name: CI

on:
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare
      run: make prepare
    - name: Test
      run: make test
